### ISSUE TITLE
 "serve": "vue-cli-service serve"

### ISSUE THREAD

**Issue by LingTaixu** [Nicnl/vue2-vite-ie11#1]
you use Vite but  "serve": "vue-cli-service serve" in package.json ?

**Comment by Nicnl** [comment]
Oops, indeed.  
Nice catch!

I initialized this project using vue-cli, and then manually converted it to Vite.  
The command line you found is a remnant from that.

Give me a few minutes and it'll be fixed.  
I'll upgrade the dependencies while I'm at it.

**Comment by Nicnl** [comment]
Done!

I've updated the depencendies, removed some unused ones (remnants from the vue-cli to vite migration) and fixed the `npm serve/build` commands.
